report :
	galaxyPATHMARK.py -z 123454321 -n 10 -b 10 merge_merged.all.tab feature.tab pid_500_pathway.tab 

clean :
	rm -rf signature.tab bootstrap_signature.tab null_signature.tab analysis report *.log .jobTree .jobTree_previous
