merge_merged_unfiltered.all.tab :
	galaxyParadigm.py -y -p small_pid_66 genome rankAllFile:data/small_pid_66_genome.tab mRNA rankAllFile:data/small_pid_66_mRNA.tab

clean :
	rm -rf signature.tab analysis report *.log .jobTree .lastTree
