all : html

html :
	shazamCytoscapeWeb.py -t input/summary.tsv -d 'input/WCDT_CNV.tab,input/WCDT_mRNA.tab,input/WCDT_mRNA.med.tab,input/merge_merged.tab' -s 3 -n 10 -p input/WCDT_abi.tab.tabular -c -i input/source_pathways/ -o html/ -l input/AbirateroneResistantKey.jpg
